### ISSUE TITLE
Highlight block option doesn't work for the underwater objects.

### ISSUE THREAD

**Issue by Yersh** [mrkite/TerraFirma#84]
Subj
For example I highlight all altars. The underwater ones are not highlighted. If the altar is partially underwater only part of it will be highlighted.
Same goes for chest and heart crystals.

**Comment by DankRank** [comment]
They do get highlighted, but it's hard to see because of the water being overlaid on top.
- without highlight:
![image](https://user-images.githubusercontent.com/4050457/50116655-792c5380-0253-11e9-9df2-66a4e1506a66.png)
- with highlight:
![image](https://user-images.githubusercontent.com/4050457/50116674-89443300-0253-11e9-8af9-2b73612c79d5.png)

**Comment by mrkite** [comment]
Need to rework highlighting to fix this.
