### ISSUE TITLE
What you see in game, differs from what you see on terrafirma

### ISSUE THREAD

**Issue by keplerk** [mrkite/TerraFirma#93]
As simple as this

In Game:
![image](https://user-images.githubusercontent.com/4659797/62830547-6990bf00-bbd6-11e9-8611-9e5a82930d0e.png)

TerraFirma
![image](https://user-images.githubusercontent.com/4659797/62830551-77464480-bbd6-11e9-9995-200a132f9949.png)

**Comment by johnbeech** [comment]
I've noticed this too: there's a fog of war switch in the menu, bit it doesn't appear to do anything.

**Comment by keplerk** [comment]
@mrkite Could you help us ?

**Comment by mrkite** [comment]
The fog of war switch blacks out anything you haven't seen so you don't need to spoil yourself if you don't want to.  If it's not doing anything, it's because it couldn't find your player save.  Right above the fog of war option there's a Select Player submenu.  You should choose your player in there.  If you're not listed, check the settings and see about setting the path.

**Comment by keplerk** [comment]
But i was talking about the differences between what i see in game and what terrafirma show me, nothing to do with that fog of war stuff.

**Comment by mrkite** [comment]
@keplerk yeah I was responding to john beech.

As far as your problem is concerned..  obviously terrafirma isn't inventing worlds so it's finding that world somewhere.  Maybe an older world cached in an old directory?  Try opening the world directly instead of using the quick selects.  If that fixes it, then again, go to settings and change the directory that terrafirma is looking.

**Comment by keplerk** [comment]
I've tried it already, opening an issue was the my last resource, on single player worlds everything its ok, but on this multiplayer it isnt.

**Comment by mrkite** [comment]
I reworked the path detection.. try the new version.
